project:
  type: website

website:
  title: "maya gans"
  
  navbar:
    title: "maya<br>gans"
    right:
      - href: blog.qmd
        text: blog
      - href: dataviz.qmd
        text: dataviz
      - href: projects.qmd
        text: projects
      - href: resume.qmd
        text: resume
        
format:
  html:
    css: inst/css/styles.css
    toc: true
    metadata:
      pagetitle: "Maya Gans"



