---
title: "Contact Me"
---

<div class="email-container">
<!-- modify this form HTML and place wherever you want your form -->
<form
  action="https://formspree.io/f/mjvzydaa"
  method="POST"
>

<label>
Your email:
<input type="email" name="email">
</label>

<label>
Your message:
<textarea name="message"></textarea>
</label>

<!-- your other form fields go here -->
<button class="maya-btn" type="submit">Send</button>
</form>
</div>

<style>
input[type=email], textarea {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

.email-container textarea {
   min-height: 150px;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.email-container {
  border-radius: 5px;
  padding: 20px;
}

.email-container label {
    width: 100%;
}

.maya-btn {
  cursor: pointer;
  position: relative;
  display: inline-block;
  padding: 8px 20px;
  margin: 10px 0;
  color: var(--accent-pink);
  border: 3px solid var(--accent-pink);
  text-decoration: none;
  text-transform: uppercase;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 2px;
  border-radius: 40px;
  overflow: hidden;
  background: white;
}

.maya-btn:hover, 
.maya-btn:focus {
  background: var(--accent-pink);
  color: white;
  border: 3px solid white;
}

</style>